package com.example.freepalestinewebview.ui.theme

import androidx.compose.ui.graphics.Color

// Palestine flag colors
val PalestineGreen = Color(0xFF007A3D)
val PalestineRed = Color(0xFFCE1126)
val PalestineBlack = Color(0xFF000000)
val PalestineWhite = Color(0xFFFFFFFF)

// Material 3 color scheme - Light
val md_theme_light_primary = PalestineGreen
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFB8F2D1)
val md_theme_light_onPrimaryContainer = Color(0xFF00210F)
val md_theme_light_secondary = PalestineRed
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFDAD6)
val md_theme_light_onSecondaryContainer = Color(0xFF410002)
val md_theme_light_tertiary = Color(0xFF4A6267)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFCDE7EC)
val md_theme_light_onTertiaryContainer = Color(0xFF051F23)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFBFDF8)
val md_theme_light_onBackground = Color(0xFF191C1A)
val md_theme_light_surface = Color(0xFFFBFDF8)
val md_theme_light_onSurface = Color(0xFF191C1A)
val md_theme_light_surfaceVariant = Color(0xFFDCE5DD)
val md_theme_light_onSurfaceVariant = Color(0xFF414942)
val md_theme_light_outline = Color(0xFF717971)
val md_theme_light_inverseOnSurface = Color(0xFFF0F1EC)
val md_theme_light_inverseSurface = Color(0xFF2E312E)
val md_theme_light_inversePrimary = Color(0xFF9CD5B6)

// Material 3 color scheme - Dark
val md_theme_dark_primary = Color(0xFF9CD5B6)
val md_theme_dark_onPrimary = Color(0xFF00391D)
val md_theme_dark_primaryContainer = Color(0xFF00522B)
val md_theme_dark_onPrimaryContainer = Color(0xFFB8F2D1)
val md_theme_dark_secondary = Color(0xFFFFB3AB)
val md_theme_dark_onSecondary = Color(0xFF680008)
val md_theme_dark_secondaryContainer = Color(0xFF930010)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDAD6)
val md_theme_dark_tertiary = Color(0xFFB1CBD0)
val md_theme_dark_onTertiary = Color(0xFF1C3438)
val md_theme_dark_tertiaryContainer = Color(0xFF324B4F)
val md_theme_dark_onTertiaryContainer = Color(0xFFCDE7EC)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF191C1A)
val md_theme_dark_onBackground = Color(0xFFE1E3DE)
val md_theme_dark_surface = Color(0xFF191C1A)
val md_theme_dark_onSurface = Color(0xFFE1E3DE)
val md_theme_dark_surfaceVariant = Color(0xFF414942)
val md_theme_dark_onSurfaceVariant = Color(0xFFC0C9C1)
val md_theme_dark_outline = Color(0xFF8A938B)
val md_theme_dark_inverseOnSurface = Color(0xFF191C1A)
val md_theme_dark_inverseSurface = Color(0xFFE1E3DE)
val md_theme_dark_inversePrimary = PalestineGreen