name: Build Palestine App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build Debug APK
      run: ./gradlew assembleDebug
    
    - name: Build Release APK (Unsigned)
      run: ./gradlew assembleRelease
    
    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: app/build/outputs/apk/debug/*.apk
    
    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: release-apk-unsigned
        path: app/build/outputs/apk/release/*unsigned*.apk
    
    - name: Create Release
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        name: Release Build ${{ github.run_number }}
        body: |
          ## Free Palestine App 🇵🇸
          
          ### 📱 Available Versions:
          
          #### Debug APK
          - For testing and development
          - Includes debugging information
          - Larger file size
          
          #### Release APK (Unsigned)
          - Optimized for production
          - Smaller file size
          - Better performance
          - Requires enabling "Install from unknown sources"
          
          ### 📥 Installation Instructions:
          1. Download the APK file (Debug or Release)
          2. Enable "Install from unknown sources" in Android settings
          3. Open the downloaded APK to install
          
          ### 🆕 What's New
          - Build from commit: ${{ github.sha }}
          - Automated build #${{ github.run_number }}
          
          ---
          **Stand with Palestine** 🇵🇸
        files: |
          app/build/outputs/apk/debug/*.apk
          app/build/outputs/apk/release/*unsigned*.apk
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      continue-on-error: true